//------------------------------------------------------------------------------
// <auto-generated>
//     此文件由 ExcelEditorWindow 自动生成，请勿手动修改！
//     扩展方法/属性请写到同名的 *BeanPartial.cs 文件中。
//     AUTO-GENERATED-DO-NOT-EDIT
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
[Serializable]
public partial class BuildItemBean : BaseBean
{
	/// <summary>
	///建筑类型
	/// </summary>
	public int build_type;
	/// <summary>
	///模型名字
	/// </summary>
	public string model_name;
	/// <summary>
	///图标
	/// </summary>
	public string icon_key;
	/// <summary>
	///图标列表
	/// </summary>
	public string icon_list;
	/// <summary>
	///tile名字
	/// </summary>
	public string tile_name;
	/// <summary>
	///是否有效
	/// </summary>
	public int valid;
	/// <summary>
	///美观值
	/// </summary>
	public float aesthetics;
	/// <summary>
	///名字
	/// </summary>
	public long name;
	[JsonIgnore]
	public string name_language { get => _name_language.Get(() => TextHandler.Instance.GetTextById(BuildItemCfg.fileName, name)); set => _name_language.Set(value); }
	private LanguageCache _name_language;
	/// <summary>
	///描述
	/// </summary>
	public long content;
	[JsonIgnore]
	public string content_language { get => _content_language.Get(() => TextHandler.Instance.GetTextById(BuildItemCfg.fileName, content, 1)); set => _content_language.Set(value); }
	private LanguageCache _content_language;
	/// <summary>
	/// Mod合并引用字段拼接（由Excel列头 [language]/[mode_id] 标记自动生成，请勿手改）：该行来自 Mod JsonText 时，下列字段按同一 modId 拼接，指向 Mod 自带配置/语言表的同自ID行；0=无引用不拼接
	/// </summary>
	public override void CombineModReferenceIds(int modId)
	{
		if (name > 0) name = BuildItemCfg.CombineModId(modId, name);
		if (content > 0) content = BuildItemCfg.CombineModId(modId, content);
	}
}
public partial class BuildItemCfg : BaseCfg<long, BuildItemBean>
{
	public static string fileName = "BuildItem";
	protected static Dictionary<long, BuildItemBean> dicData = null;
	public static Dictionary<long, BuildItemBean> GetAllData()
	{
		if (dicData == null)
		{
			var arrayData = GetAllArrayData();
			InitData(arrayData);
		}
		return dicData;
	}
	public static BuildItemBean[] GetAllArrayData()
	{
		if (arrayData == null)
		{
			arrayData = GetInitData(fileName);
			arrayData = System.Array.FindAll(arrayData, itemData => itemData.valid != 0);
		}
		return arrayData;
	}
	public static BuildItemBean GetItemData(long key)
	{
		if (dicData == null)
		{
			InitData(GetAllArrayData());
		}
		return GetItemData(key, dicData);
	}
	public static void InitData(BuildItemBean[] arrayData)
	{
		dicData = new Dictionary<long, BuildItemBean>();
		for (int i = 0; i < arrayData.Length; i++)
		{
			BuildItemBean itemData = arrayData[i];
			dicData.Add(itemData.id, itemData);
		}
	}
}
