//------------------------------------------------------------------------------
// <auto-generated>
//     此文件由 ExcelEditorWindow 自动生成，请勿手动修改！
//     扩展方法/属性请写到同名的 *BeanPartial.cs 文件中。
//     AUTO-GENERATED-DO-NOT-EDIT
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
[Serializable]
public partial class TextLookBean : BaseBean
{
	/// <summary>
	///type
	/// </summary>
	public int type;
	/// <summary>
	///mark_id
	/// </summary>
	public long mark_id;
	/// <summary>
	///text_order
	/// </summary>
	public int text_order;
	/// <summary>
	///user_id
	/// </summary>
	public long user_id;
	/// <summary>
	///名字
	/// </summary>
	public long name;
	[JsonIgnore]
	public string name_language { get => _name_language.Get(() => TextHandler.Instance.GetTextById(TextLookCfg.fileName, name)); set => _name_language.Set(value); }
	private LanguageCache _name_language;
	/// <summary>
	///内容
	/// </summary>
	public long content;
	[JsonIgnore]
	public string content_language { get => _content_language.Get(() => TextHandler.Instance.GetTextById(TextLookCfg.fileName, content, 1)); set => _content_language.Set(value); }
	private LanguageCache _content_language;
	/// <summary>
	/// Mod合并引用字段拼接（由Excel列头 [language]/[mode_id] 标记自动生成，请勿手改）：该行来自 Mod JsonText 时，下列字段按同一 modId 拼接，指向 Mod 自带配置/语言表的同自ID行；0=无引用不拼接
	/// </summary>
	public override void CombineModReferenceIds(int modId)
	{
		if (name > 0) name = TextLookCfg.CombineModId(modId, name);
		if (content > 0) content = TextLookCfg.CombineModId(modId, content);
	}
}
public partial class TextLookCfg : BaseCfg<long, TextLookBean>
{
	public static string fileName = "TextLook";
	protected static Dictionary<long, TextLookBean> dicData = null;
	public static Dictionary<long, TextLookBean> GetAllData()
	{
		if (dicData == null)
		{
			var arrayData = GetAllArrayData();
			InitData(arrayData);
		}
		return dicData;
	}
	public static TextLookBean[] GetAllArrayData()
	{
		if (arrayData == null)
		{
			arrayData = GetInitData(fileName);
		}
		return arrayData;
	}
	public static TextLookBean GetItemData(long key)
	{
		if (dicData == null)
		{
			TextLookBean[] arrayData = GetInitData(fileName);
			InitData(arrayData);
		}
		return GetItemData(key, dicData);
	}
	public static void InitData(TextLookBean[] arrayData)
	{
		dicData = new Dictionary<long, TextLookBean>();
		for (int i = 0; i < arrayData.Length; i++)
		{
			TextLookBean itemData = arrayData[i];
			dicData.Add(itemData.id, itemData);
		}
	}
}
