using UnityEngine;
using UnityEditor;

public enum ImportantTypeEnum
{
    Camera2D,
    Camera,
    MainCamera,
    GameUI,
    DialogManager,
    ToastManager,

    Init,
    GameDataManager,
    GameItemsManager,
    FoodManager,
    CharacterManager,
    NpcManager,
    UIManager,
    StoryManager,
    SceneManager,
    StoreInfoManager,
    BuildManager,
    AudioManager,
    TextManager,
    EffectManager,
    SkillManager,

    StoryBuilder,
    NpcBuilder,
    InnBuilder,
    MiniGameBuilder,
    SceneBuilder,
    GambleBuilder,

    GameDataHandler,
    EventHandler,
    TimeHandler,
    ControlHandler,
    WeatherHandler,
    LightHandler,
    EcologyHandler,
    MiniGameHandler,
    InnHandler,
    AudioHandler,
    SceneHandler,
    EffectHandler,
    GambleHandler,
    CursorHandler,
    SkillHandler,

    Popup,
    Sun,
    Steam,
}